### ISSUE TITLE
Facebook JSON not more available

### ISSUE THREAD

**Issue by echavanon** [mpratt/The-Simple-LifeStream#9]
Hello,

Facebook changed the way they provide data
"
The Pages JSON feed (e.g. https://www.facebook.com/feeds/page.php?id=%2019292868552&format=json) is now deprecated and will stop returning data from Jan 28, 2015 onwards. Developers should instead call the feed edge on the Graph API's Page object: /v2.2/{page_id}/feed. 
"
So This tool is unaware to manage the stream anymore.

Source :
https://developers.facebook.com/docs/apps/changelog?locale=fr_FR#v2_2_90_day_deprecations

Have a nice day.

**Comment by QWp6t** [comment]
FacebookPages could be refactored to extend the Feed class with the following URL:
`https://www.facebook.com/feeds/page.php?format=rss20&id={page_id}`

Or we can just switch over to Graph API, which I suspect is more work.

**Comment by QWp6t** [comment]
I took the liberty of doing just that. It passes phpunit real world test, but I haven't actually tried it with an app yet. Feel free to test it, and use it if works for you. Meanwhile I'll look into Graph API since that might be the smarter way to go (after all, Facebook specifically requests that we use it).

```php
<?php
/**
 * FacebookPages.php
 *
 * @package Providers
 * @author  Michael Pratt <pratt@hablarmierda.net>
 * @link    http://www.michael-pratt.com/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace SimpleLifestream\Providers;

/**
 * A provider for Facebook Pages
 */
class FacebookPages extends Feed
{
    /** inline {@inheritdoc} */
    protected $settings = array(
        'content_length' => '80',
        'content_delimiter' => '...',
    );

    /** inline {@inheritdoc} */
    public function __construct(array $settings)
    {
        $settings = array(
            'type' => 'link',
            'service' => 'facebookpages',
            'resource' => 'http://www.facebook.com/feeds/page.php?format=rss20&id=' . $settings['resource'],
            'resource_name' => $settings['resource']
        );

        parent::__construct($settings);
    }

    /** inline {@inheritdoc} */
    protected function rss()
    {
        $return = array();
        foreach ($this->xml->channel->item as $item)
        {
            $return[] = array(
                'service'  => $this->settings['service'],
                'type'     => $this->settings['type'],
                'stamp'    => (int) strtotime($item->pubDate),
                'text'     => (string) $this->getStatusText($item),
                'url'      => (string) $item->link,
                'resource' => (string) $item->author,
            );
        }

        return $return;
    }

    /**
     * Retrieves text from either item title or content
     *
     * @param SimpleXMLElement $item
     * @return string
     */
    protected function getStatusText(\SimpleXMLElement $item)
    {
        $text = $item->link;
        
        if (trim($item->title) !== '')
            $text = $item->title;
        else if (trim(strip_tags($item->description)) !== '')
            $text = strip_tags($item->description);

        return $this->truncate(trim($text));
    }

    /**
     * Truncates the $text
     *
     * @param string $text
     * @return string
     */
    protected function truncate($text)
    {
        if (strlen($text) > $this->settings['content_length']) {
            return substr($text, 0, $this->settings['content_length']) . $this->settings['content_delimiter'];
        }

        return $text;
    }
}

?>
```

**Comment by mpratt** [comment]
Hi @echavanon, thank you very much for the report.

@QWp6t Thanks for finding a suitable workaround for now. I overwrote the `FacebookPages` class with the one you provided. I did some minor changes and added new tests and it all seems to be working fine.

There are some exceptions, lets take a look for example to [Coca Cola's facebook page](https://www.facebook.com/cocacola). The Url should be https://www.facebook.com/feeds/page.php?id=40796308305&format=rss20 and the response is:

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
      xmlns:media="http://search.yahoo.com/mrss/"
      xmlns:dc="http://purl.org/dc/elements/1.1/"
    >
  <channel>
    <title>Coca-Cola&apos;s Facebook Wall</title>
    <link>https://www.facebook.com/</link>
    <description>Coca-Cola&apos;s Facebook Wall</description>
    <language>en-us</language>
    <category domain="Facebook">PageSyndicationFeed</category>
    <generator>Facebook Syndication</generator><docs>http://www.rssboard.org/rss-specification</docs>
    <webMaster>webmaster@facebook.com</webMaster>
  </channel>
  <access:restriction relationship="deny" xmlns:access="http://www.bloglines.com/about/specs/fac-1.0" />
</rss>
```

I dont know if this happened with the json response before too, but the `<access:restriction relationship="deny" xmlns:access="http://www.bloglines.com/about/specs/fac-1.0" />` prevents the user from getting the posts from the page.

I was trying to avoid using oauth2 in order to keep things simple, but it seems as it is something we have to do in the future. On the other hand the best way might be to use the [PHP SDK](https://developers.facebook.com/docs/reference/php/4.0.0) and also give support for user posts, statuses, etc using the [/{user}/feed](https://developers.facebook.com/docs/graph-api/reference/v2.2/user/feed) call on the GRAPH API.

I'm not a fan of introducing dependencies into this library. As of now I still believe the library is still "simple" and the plan is to keep it that way. So the first thing that comes into my mind is to create a new provider that would be called something like `FacebookGraph` and in order to use it, you need to use facebook's PHP SDK and write some minor code. 

This is what I Have in Mind (Obviously, the user needs to create an APP in facebook):

```php
FacebookSession::setDefaultApplication('THE_APP_ID', 'THE_APP_SECRET');
$fbSession = new FacebookSession('access token here');

$streams = array(
    new \SimpleLifestream\Stream('FacebookGraph', $fbSession),
);

$lifestream = new \SimpleLifestream\SimpleLifestream($config);
$data = $lifestream->loadStreams($streams)->getLifestream();
var_dump($data);
```

Under the covers, the library only needs to do implement something short:

```php
class FacebookGraph extends Adapter
{
    public function getApiData()
    {
        if (!$settings['resource'] instaceof FacebookSession) {
            .... throw exception ....
         }
         $request = new FacebookRequest($this->settings['resource'], 'GET', '/me/feed');
         if ($response = $request->execute()) {
               return $this->filterResponse($response->getGraphObject());
         }
        return null;
    }

    protected function filterResponse(GraphObject $graphObject = null)
    {
        ... do that thing ...
    }
}
```

That would be more or less what I have in mind. Perhaps for composer users, we can suggest the SDK, so that everyone is happy.  

```
"suggest": {
       "facebook/php-sdk-v4" : "Version 4.0 in order to use the FacebookGraph provider"
    }
```

Right now I dont have enough time to look into this much further, so If you want to take a shot at implementing this or if you have other idea on how to implement, please let me know. Otherwise you'll have to wait until next month or around the end of March.

Thank you again!

**Comment by QWp6t** [comment]
https://www.facebook.com/cocacola redirects to `/CocaColaUnitedStates&brand_redir=1`, the page ID for which is `820882001277849`.

All of this is to say that this works: https://www.facebook.com/feeds/page.php?format=rss20&id=820882001277849

**Comment by mpratt** [comment]
That's funny, since I don't live in the US https://www.facebook.com/cocacola doesnt redirect me anywhere and perhaps that is why I get the "access:restriction" stuff.

Anyways, the provider works with your solution and for that I'm very grateful!
On the other hand I would love to hear your opinion about the possible `FacebookGraph` provider :+1:
